### ISSUE TITLE
`tasty-hspec` doesn't respect --hide-successes

### ISSUE THREAD

**Issue by parsonsmatt** [mitchellwrosen/tasty-hspec#16] opened 2018-03-05 20:21 UTC
See [tasty #213](https://github.com/feuerbach/tasty/issues/213) for original discussion.

`tasty-hspec` apparently prints out all of the tests when `--hide-successes` is passed on the command-line. This is not the intended behavior of the flag -- it should hide the entire test, not just the successful output.

**Comment by mitchellwrosen** [comment] 2018-03-05 20:55
Indeed the only options from `OptionSet` we respect are QuickCheck and SmallCheck pass-thrus - none of the built-in options from https://hackage.haskell.org/package/tasty-1.0.1/docs/Test-Tasty-Options.html#t:IsOption:

- TestPattern
- Timeout
- NumThreads
- ListTests
- UseColor
- HideSuccesses	 
- Quiet

**Comment by mitchellwrosen** [comment] 2018-03-05 21:53
Hm, @feuerbach could you please clarify why you think this is an issue with `tasty-hspec`? This package only re-jiggers an hspec spec into a tasty tree, but is not responsible for top-level "run" configurations, like hiding the output of successful tests.

But in addition, I was unable to reproduce the issue with this test suite:

```haskell
import Test.Hspec
import Test.Tasty
import Test.Tasty.Hspec

spec :: Spec
spec =
  it "does something" $
    1 `shouldBe` 1

main :: IO ()
main = do
  tree <- testSpec "hspec suite" spec
  defaultMain tree
```

When I run e.g. `stack test --test-arguments=--hide-successes`, I see no indication that a test named `"does something"` was run. It just says 1 test passed.

**Comment by feuerbach** [comment] 2018-03-05 22:20
Sorry, that was just my guess — I didn't try to reproduce the issue. It could be that the output is coming from somewhere else in the test suite.

**Comment by mitchellwrosen** [comment] 2018-03-19 19:37
@parsonsmatt Any update on this?

**Comment by mitchellwrosen** [comment] 2018-06-27 20:01
I'm going to close this out as I couldn't reproduce, but please re-open if I've overlooked something.

**Closed by mitchellwrosen** 2018-06-27 20:01 UTC
